routes/web.php
<?php

use App\Http\Controllers\Admin\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\ChecklistGroupController;
use App\Http\Controllers\Admin\ChecklistController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\PageController as ControllersPageController;
use App\Http\Controllers\User\ChecklistController as UserChecklistController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'welcome');

Auth::routes();


Route::group(['middleware' => ['auth', 'save_last_action_timestamp']], function () {
    Route::get('welcome', [ControllersPageController::class, 'welcome'])->name('welcome');
    Route::get('consultation', [ControllersPageController::class, 'consultation'])->name('consultation');
    Route::get('checklists/{checklist}', [UserChecklistController::class, 'show'])->name('user.checklists.show');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'is_admin'], function () {
        Route::resource('pages', PageController::class)->only(['edit', 'update']);
        Route::resource('checklist_groups', ChecklistGroupController::class);
        Route::resource('checklist_groups.checklists', ChecklistController::class);
        Route::resource('checklists.tasks', TaskController::class);
        Route::get('users', [UserController::class, 'index'])->name('users.index');
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        
    });
});

resources/views/partials/sidebar.blade.php
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
    <ul class="c-sidebar-nav">

        @if (auth()->user()->is_admin)


        <li class="c-sidebar-nav-title">{{ ('Manage Checklists') }}</li>

        @foreach ($admin_menu as $group)
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown c-show"><a class="c-sidebar-nav-link"
                href="{{route('admin.checklist_groups.edit', $group->id)}}">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-folder-open')}}"></use>
                </svg> {{$group->name}}
            </a>
            <ul class="c-sidebar-nav-dropdown-items">
                @foreach ($group->checklists as $checklist)
                <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" style="padding: .5rem .5rem .5rem 76px"
                        href="{{route('admin.checklist_groups.checklists.edit', [$group,$checklist])}}"><span
                            class="c-sidebar-nav-icon"></span>
                        <svg class="c-sidebar-nav-icon">
                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-list')}}"></use>
                        </svg>{{$checklist->name}}
                    </a>
                </li>
                @endforeach
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" style="padding: 1rem .5rem .5rem 76px"
                        href="{{route('admin.checklist_groups.checklists.create', $group)}}">
                        <svg class="c-sidebar-nav-icon">
                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-note-add')}}"></use>
                        </svg>
                        {{__('New Checklist')}}</a>
            </ul>
        </li>
        @endforeach
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
            <a class="c-sidebar-nav-link" href="{{route('admin.checklist_groups.create')}}">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-library-add')}}"></use>
                </svg>
                {{__('New Checklist
                group')}}</a>
        </li>

        <li class="c-sidebar-nav-title">{{ ('Manage Data') }}</li>
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link"
                href="{{route('admin.users.index')}}">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-puzzle')}}"></use>
                </svg> {{ __('Users')}}</a>
        </li>
        @else
        @foreach ($user_menu as $group)
        <li class="c-sidebar-nav-title">{{$group['name'] }}
            @if ($group['is_new'])
            <span class="badge badge-info">NEW</span>
            @elseif($group['is_updated'])
            <span class="badge badge-info">UPD</span>
            @endif
        </li>

        @foreach ($group['checklists'] as $checklist)
        <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link"
                href="{{route('user.checklists.show', [$checklist['id']]) }}"><span class="c-sidebar-nav-icon"></span>
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-list')}}"></use>
                </svg>
                {{$checklist['name']}}

                @livewire('completed-tasks-counter', [
                'completed_tasks' => count($checklist['user_tasks']),
                'tasks_count' => count($checklist['tasks']),
                'checklist_id' => $checklist['id']
                ])

                @if ($checklist['is_new'])
                <span class="badge badge-info">NEW</span>
                @elseif($checklist['is_updated'])
                <span class="badge badge-info">UPD</span>
                @endif
            </a>

        </li>
        @endforeach

        @endforeach

        @endif

    </ul>
    <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent"
        data-class="c-sidebar-minimized"></button>
</div>