routes/web.php
<?php

use App\Http\Controllers\Admin\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\ChecklistGroupController;
use App\Http\Controllers\Admin\ChecklistController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\PageController as ControllersPageController;
use App\Http\Controllers\User\ChecklistController as UserChecklistController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'welcome');

Auth::routes();


Route::group(['middleware' => ['auth', 'save_last_action_timestamp']], function () {
    Route::get('welcome', [ControllersPageController::class, 'welcome'])->name('welcome');
    Route::get('consultation', [ControllersPageController::class, 'consultation'])->name('consultation');
    Route::get('checklists/{checklist}', [UserChecklistController::class, 'show'])->name('user.checklists.show');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'is_admin'], function () {
        Route::resource('pages', PageController::class)->only(['edit', 'update']);
        Route::resource('checklist_groups', ChecklistGroupController::class);
        Route::resource('checklist_groups.checklists', ChecklistController::class);
        Route::resource('checklists.tasks', TaskController::class);
        Route::get('users', [UserController::class, 'index'])->name('users.index');
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        
    });
});

app/Http/Livewire/ChecklistShow.php
<?php

namespace App\Http\Livewire;

use App\Models\Task;
use Livewire\Component;

class ChecklistShow extends Component
{
    public $checklist;
    public $opened_tasks = [];
    public $completed_tasks = [];

    public function mount()
    {
        $this->completed_tasks = Task::where('checklist_id', $this->checklist->id)
        ->where('user_id', auth()->id())
        ->whereNotNull('completed_at')->pluck('task_id')->toArray();
        // $this->current_task = NULL;
        // $this->reminder_date = now()->addDay()->toDateString();
        // $this->reminder_hour = now()->hour;
    }


    public function render()
    {
        return view('livewire.checklist-show');
    }
    public function toggle_task($task_id){
        if(in_array($task_id, $this->opened_tasks)){
            $this->opened_tasks = array_diff($this->opened_tasks, [$task_id]);
        } else{
            $this->opened_tasks[] = $task_id;

        }
    }

    public function complete_task($task_id)
    {
        $task = Task::find($task_id);
        if ($task) {
            $user_task = Task::where('task_id', $task_id)
                ->where('user_id', auth()->id())
                ->first();
            if ($user_task) {
                if (is_null($user_task->completed_at)) {
                    $user_task->update(['completed_at' => now()]);
                    $this->completed_tasks[] = $task_id;
                    $this->emit('task_complete', $task_id, $task->checklist_id);
                } else {
                    $user_task->delete();
                    $this->emit('task_complete', $task_id, $task->checklist_id, -1);
                 }
            } else {
                $user_task = $task->replicate();
                $user_task['user_id'] = auth()->id();
                $user_task['task_id'] = $task_id;
                $user_task['completed_at'] = now();
                $user_task->save();
                $this->completed_tasks[] = $task_id;
                $this->emit('task_complete', $task_id, $task->checklist_id);

            }
        }
    }
}

app/Http/Livewire/CompletedTasksCounter.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class CompletedTasksCounter extends Component
{
    public $completed_tasks = 0;
    public $tasks_count = 0;
    public $checklist_id;
    public function render()
    {
        return view('livewire.completed-tasks-counter');
    }
    public function recalculate_tasks($task_id, $checklist_id, $count_change = 1)
    {
        if ($checklist_id == $this->checklist_id) {
            $this->completed_tasks += $count_change;
        }
    }
}

app/Http/Livewire/HeaderTotalsCount.php
<?php

namespace App\Http\Livewire;

use App\Models\Checklist;
use Livewire\Component;

class HeaderTotalsCount extends Component
{
    public $checklist_group_id;
    protected $listeners = ['task_complete' => 'render'];

    public function render()
    {
        $checklists = Checklist::where('checklist_group_id', $this->checklist_group_id)
        ->whereNull('user_id')
        ->withCount(['tasks' => function($query) {
            $query->whereNull('user_id');
        }])
        ->withCount(['user_tasks' => function($query) {
            $query->whereNotNull('completed_at');
        }])
        ->get();
        return view('livewire.header-totals-count', compact('checklists'));
    }
}

app/Http/Livewire/TaskTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Task;
use Livewire\Component;

class TaskTable extends Component
{
    public $checklist;
    public function render()
    {
        $tasks = $this->checklist->tasks()->where('user_id', NULL)->orderBy('position')->get();
        return view('livewire.task-table', compact('tasks'));
    }
    public function task_up($task_id)
    {
        $task = Task::find($task_id);
        if ($task) {
            Task::whereNull('user_id')->where('position', $task->position - 1)->update([
                'position' => $task->position
            ]);
            $task->update(['position' => $task->position - 1]);
        }
    }

    public function task_down($task_id)
    {
        $task = Task::find($task_id);
        if ($task) {
            Task::whereNull('user_id')->where('position', $task->position + 1)->update([
                'position' => $task->position
            ]);
            $task->update(['position' => $task->position + 1]);
        }
    }
}

resources/views/livewire/checklist-show.blade.php
                <table class="table">
                    @foreach ($checklist->tasks->where('user_id', NULL) as $task)

                    <tr>
                        <td> <input  type="checkbox" wire:click = "complete_task({{$task->id}})"
                            @if (in_array($task->id, $completed_tasks)) checked="checked" @endif  />
                            
                             
                        </td>
                        <td wire:click = "toggle_task({{$task->id}})">{{$task->name}} </td>
                        <td wire:click = "toggle_task({{$task->id}})" >
                    @if (in_array($task->id, $opened_tasks))
                            <svg class="c-sidebar-nav-icon">
                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-caret-top')}}">
                                </use>
                            </svg>
                            @else

                            <svg class="c-sidebar-nav-icon">
                                <use
                                    xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-caret-bottom')}}">
                                </use>
                            </svg>
                            @endif
                        </td>
                    </tr>
                    @if (in_array($task->id, $opened_tasks))
                    <tr>
                        <td></td>
                        <td colspan="2">{!! $task->description !!}</td>
                    </tr>
                    @endif
                    

                    @endforeach
                </table>
            </div>

        </div>
    </div>

resources/views/livewire/completed-tasks-counter.blade.php
<span class="badge badge-info">
    {{$completed_tasks}} / {{$tasks_count}}
</span>

resources/views/livewire/header-totals-count.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                {{ __('Store Review') }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        @foreach ($checklists as $checklist)
                            <div class="row mb-2">
                                <div class="col-md-5 text-right">
                                    <a class="font-weight-bold"
                                       href="{{ route('user.checklists.show', $checklist->id) }}">{{ $checklist->name }}</a>
                                </div>
                                <div class="col-md-7">
                                    <div class="progress progress-xs mt-2 mb-1">
                                        @if ($checklist->tasks_count > 0)
                                            <div class="progress-bar bg-success" role="progressbar"
                                                 style="width: {{ $checklist->user_tasks_count / $checklist->tasks_count * 100 }}%"
                                                 aria-valuenow="{{ $checklist->user_tasks_count / $checklist->tasks_count * 100 }}"
                                                 aria-valuemin="0"
                                                 aria-valuemax="100">
                                            </div>
                                        @else
                                            <div class="progress-bar bg-success" role="progressbar"
                                                 style="width: 0%"
                                                 aria-valuenow="0"
                                                 aria-valuemin="0"
                                                 aria-valuemax="100">
                                            </div>
                                        @endif
                                    </div>
                                    <strong>{{ $checklist->user_tasks_count }}/{{ $checklist->tasks_count }}</strong>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    <div class="col-md-4">
                        <h2>{{ $checklists->sum('user_tasks_count') }}/{{ $checklists->sum('tasks_count') }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/task-table.blade.php
<table class="table table-responsive-sm">

    <tbody>
        @foreach ($tasks as $task )

        <tr>
            <td>
                @if ($task->position > 1)
                <a wire:click.prevent="task_up({{ $task->id }})" href="#">
                    &uarr;
                </a>
                @endif
                @if ($task->position < $tasks->max('position'))
                <a wire:click.prevent="task_down({{ $task->id }})" href="#">
                    &darr;
                </a>
                @endif
            </td>
            <td>{{$task->name}}</td>
            {{-- <td>{!!$task->description!!}</td> --}}
            <td>
                <a class="btn btn-sm btn-primary"
                    href="{{ route('admin.checklists.tasks.edit', [$checklist, $task]) }}">{{__('Edit')}}</a>
                <form style="display: inline-block"
                    action="{{ route('admin.checklists.tasks.destroy', [$checklist, $task]) }}"
                    method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-sm btn-danger" type="submit"
                        onclick="return confirm('{{ __('Are you sure?') }}')"> {{
                        __('Delete') }}</button>
                </form>
            </td>
        </tr>
        @endforeach

    </tbody>
</table>